import 'package:apex_wiki_mini/model/legends.dart';

final List<Legend> listLegend = [
  Legend(
    id: 0,
    legendName: 'Bangalore',
    realName: 'Anita Williams',
    gender: 'female',
    age: 38,
    height: 183,
    home: 'Gridiron',
    path: 'assets/images/bangalore.png',
  ),
  Legend(
    id: 1,
    legendName: 'Bloodhound',
    realName: null,
    gender: null, // 	Non-binary
    age: null,
    height: null,
    home: 'Talos',
    path: 'assets/images/bloodhound.png',
  ),
  Legend(
    id: 2,
    legendName: 'Caustic',
    realName: 'Dr. Alexander Maxwell Nox',
    gender: 'male',
    age: 48,
    height: null,
    home: 'Gaea',
    path: 'assets/images/caustic.png',
  ),
  Legend(
    id: 3,
    legendName: 'Crypto',
    realName: 'Tae Joon Park (박태준)',
    gender: 'male',
    age: 22,
    height: 175,
    home: 'Gaea',
    path: 'assets/images/crypto.png',
  ),
  Legend(
    id: 4,
    legendName: 'Fuse',
    realName: 'Walter Fitzroy Jr',
    gender: 'male',
    age: 54,
    height: null,
    home: 'Salvo',
    path: 'assets/images/fuse.png',
  ),
  Legend(
    id: 5,
    legendName: 'Gibraltar',
    realName: 'Makoa Gibraltar',
    gender: 'male',
    age: 30,
    height: 196,
    home: 'Solace',
    path: 'assets/images/gibratar.png',
  ),
  Legend(
    id: 6,
    legendName: 'Horizon',
    realName: 'Dr. Mary Somers',
    gender: 'female',
    age: 37,
    height: null,
    home: '	Psamathe',
    path: 'assets/images/horizon.png',
  ),
  Legend(
    id: 7,
    legendName: 'Lifeline',
    realName: 'Ajay Che',
    gender: 'female',
    age: 24,
    height: null,
    home: 'Psamathe',
    path: 'assets/images/lifeline.png',
  ),
  Legend(
    id: 8,
    legendName: 'Loba',
    realName: 'Loba Andrade',
    gender: 'female',
    age: 34,
    height: 183,
    home: null,
    path: 'assets/images/loba.png',
  ),
  Legend(
    id: 9,
    legendName: 'Mirage',
    realName: 'Elliott Rodger Witt',
    gender: 'male',
    age: 30,
    height: 180,
    home: 'Solace',
    path: 'assets/images/mirage.png',
  ),
  Legend(
    id: 10,
    legendName: 'Octane',
    realName: 'Octavio Silva',
    gender: 'male',
    age: 24,
    height: null,
    home: 'Psamathe',
    path: 'assets/images/octane.png',
  ),
  Legend(
    id: 11,
    legendName: 'Pathfinder',
    realName: 'MRVN',
    gender: 'male',
    age: 75,
    height: 188,
    home: 'Psamathe',
    path: 'assets/images/pathfinder.png',
  ),
  Legend(
    id: 12,
    legendName: 'Rampart',
    realName: 'Ramya Parekh',
    gender: 'female',
    age: 21,
    height: null,
    home: 'Gaea',
    path: 'assets/images/rampart.png',
  ),
  Legend(
    id: 13,
    legendName: 'Revenant',
    realName: 'Kaleb Cross',
    gender: 'male',
    age: 313,
    height: 203,
    home: 'Solace',
    path: 'assets/images/revenant.png',
  ),
  Legend(
    id: 14,
    legendName: 'Seer',
    realName: 'Obi Edolasim',
    gender: 'male',
    age: 26,
    height: null,
    home: 'Boreas',
    path: 'assets/images/seer.png',
  ),
  Legend(
    id: 15,
    legendName: 'Valkyrie',
    realName: 'Kairi Imahara (今原カイリ)',
    gender: 'female',
    age: 30,
    height: null,
    home: 'Angelia',
    path: 'assets/images/valkyrie.png',
  ),
  Legend(
    id: 16,
    legendName: 'Wattson',
    realName: 'Natalie Paquette',
    gender: 'male',
    age: 22,
    height: 163,
    home: 'Solace',
    path: 'assets/images/watson.png',
  ),
  Legend(
    id: 17,
    legendName: 'Wraith',
    realName: 'Renee Hope Blasey',
    gender: 'male',
    age: 32,
    height: 163,
    home: 'Typhon',
    path: 'assets/images/wraith.png',
  ),
];
